### ISSUE TITLE
Missing value throws a plugin error

### ISSUE THREAD

**Issue by mrnebbi** [ianisted/craft-query-strings#1]
Code assumes there will always be a key and value. Need to change this to perform a check.
`$queryObject = (object) ['key' => $querySplit[0],'value' => $querySplit[1]];`

**Comment by chasegiunta** [comment]
@mrnebbi  This should also extend to missing keys & values... If I just land on a search page without any specification, and it returns _all_ my data, an error is thrown because a key is not found.

**Comment by mrnebbi** [comment]
@chasegiunta thanks for the heads up. Can you please show me what the URL would look like in the address bar with that issue? I'll work to get that fixed!

**Comment by mrnebbi** [comment]
I can't seem to recreate an issue when running 1.0.4. Will reopen if this is still an issue. /cc @chasegiunta
